#- include: add_repo.yml

- name: Install packages
  yum:
    name:
      - centreon-base-config-centreon-engine 
      - centreon-widget*
    state: present
#    disablerepo: "*"
#    enablerepo: "{{ centreon_local_repo_id }}"

- include: config.yml
