
centreon_poller_name: "{{ ansible_hostname }}"
centreon_poller_current_ip_number: 1
centreon_poller_register_central: y

vg_name: "central_vg"
raw_disks: [ /dev/sdb ]

lv_elements: 
  - { 
    lv_name: "lv_log",
    require_lv_size: "10M",
    fs: "xfs",
    mount_point: "/var/log",
    create_mount_point: true
 }
  - { 
    lv_name: "lv_centreon_broker",
    require_lv_size: "10M",
    fs: "xfs",
    mount_point: "/var/lib/centreon-broker",
    create_mount_point: true
 }
  - { 
    lv_name: "lv_centreon_backup",
    require_lv_size: "10M",
    fs: "xfs",
    mount_point: "/var/lib/centreon/backup",
    create_mount_point: true

 }
  - { 
    lv_name: "lv_centreon_plugins",
    require_lv_size: "5M",
    fs: "xfs",
    mount_point: "/var/lib64/nagios/plugins",
    create_mount_point: true
 }

